name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Lint sources
        run: npm run lint
      - name: Lint styles
        run: npm run lint:css
      - name: Run unit tests
        run: npm run test:unit
      - name: Build client
        run: npm run build
      - name: Run end-to-end tests
        run: npm run test:e2e
